// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

namespace FiroozehCorp.ZigZagGame.scripts.data
{
        ///
        /// This file is automatically generated DO NOT EDIT!
        ///
        /// These are the constants defined in the Play Games Console for Game Services
        /// Resources.
        ///


        public static class GPGSIds
        {
                public const string achievement_skilled_tapper = "achievement_skilled_tapper"; // <GPGSID>
                public const string achievement_apprentice_tapper = "achievement_apprentice_tapper"; // <GPGSID>
                public const string achievement_respected_tapper = "achievement_respected_tapper"; // <GPGSID>
                public const string event_attempts = "event_attempts"; // <GPGSID>
                public const string achievement_experienced_tapper = "achievement_experienced_tapper"; // <GPGSID>
                public const string leaderboard_high_score = "leaderboard_high_score"; // <GPGSID>
                public const string event_high_score = "event_high_score"; // <GPGSID>
                public const string achievement_feared_tapper = "achievement_feared_tapper"; // <GPGSID>
                public const string achievement_starter_tapper = "achievement_starter_tapper"; // <GPGSID>
                public const string achievement_novice_tapper = "achievement_novice_tapper"; // <GPGSID>

        }
}

